version: 2
updates:
  - directory: /
    open-pull-requests-limit: 3
    package-ecosystem: "gitsubmodule"
    rebase-strategy: auto
    allow:
      - dependency-name: "scripts/types"
    schedule:
      interval: "daily"
