"menus" 
{

    "P2CE"
    {
        "name" "Portal 2 Community Edition"
        "icon" "file://{images}/menu/p2ce/logo.png"
        "background" "file://{media}/community_bg1.webm"
        "publisher" "Chaos Initative"
        "maps"
        {
            0
            {   
                "name" "TRIPLE LASER"
                "image" "file://{p2chapters}/chapter2.vtf"
                "map" "sp_a2_triple_laser"
            }
        }
    }

    "P2"
    {
        "name" "Portal 2"
        "icon" "file://{images}/menu/portal2/logo.png"
        "background" "file://{media}/menu_act01.webm"
        "publisher" "Valve"
        "maps"
        {
            0
            {   
                "name" "#portal2_Chapter1_Subtitle"
                "image" "file://{p2chapters}/chapter1.vtf"
                "map" "sp_a1_intro1"
            }
            1
            {   
                "name" "#portal2_Chapter2_Subtitle"
                "image" "file://{p2chapters}/chapter2.vtf"
                "map" "sp_a2_laser_intro"
            }
            2
            {   
                "name" "#portal2_Chapter3_Subtitle"
                "image" "file://{p2chapters}/chapter3.vtf"
                "map" "sp_a2_sphere_peek"
            }
            3
            {   
                "name" "#portal2_Chapter4_Subtitle"
                "image" "file://{p2chapters}/chapter4.vtf"
                "map" "sp_a2_column_blocker"
            }
            4
            {   
                "name" "#portal2_Chapter5_Subtitle"
                "image" "file://{p2chapters}/chapter5.vtf"
                "map" "sp_a2_bts3"
            }
            5
            {   
                "name" "#portal2_Chapter6_Subtitle"
                "image" "file://{p2chapters}/chapter6.vtf"
                "map" "sp_a3_00"
            }
            7
            {   
                "name" "#portal2_Chapter7_Subtitle"
                "image" "file://{p2chapters}/chapter7.vtf"
                "map" "sp_a3_speed_ramp"
            }
            7
            {   
                "name" "#portal2_Chapter8_Subtitle"
                "image" "file://{p2chapters}/chapter8.vtf"
                "map" "sp_a4_intro"
            }
            8
            {   
                "name" "#portal2_Chapter9_Subtitle"
                "image" "file://{p2chapters}/chapter9.vtf"
                "map" "sp_a4_finale1"
            }
        }
    }

    "P2C"
    {
        "name" "Portal 2 Co-op"
        "icon" "file://{images}/menu/portal2/p2_coop_icon.png"
        "background" "file://{media}/menu_act01.webm"
        "publisher" "Valve"
        "maps"
        {
            0
            {   
                "name" "#portal2_Chapter1_Subtitle"
                "image" "file://{p2chapters}/chapter1.vtf"
                "map" "sp_a1_intro1"
            }
        }
    }
}