"menus" 
{

    "P2CE"
    {
        "name" "Portal 2 Community Edition"
        "icon" "file://{images}/menu/p2ce/logo.png"
        "background" "file://{media}/community_bg1.webm"
        "publisher" "Chaos Initative"
        "maps"
        {
            0
            {   
                "name" "Triple Laser"
                "image" "file://{p2chapters}/chapter2.vtf"
                "map" "sp_a2_triple_laser"
            }
        }
    }

    "P2"
    {
        "name" "Portal 2"
        "icon" "file://{images}/menu/portal2/logo.png"
        "background" "file://{media}/menu_act01.webm"
        "publisher" "Valve"
        "maps"
        {
            0
            {   
                "name" "#portal2_Chapter1_Title"
                "image" "file://{p2chapters}/chapter1.vtf"
                "map" "sp_a1_intro1"
            }
            1
            {   
                "name" "#portal2_Chapter2_Title"
                "image" "file://{p2chapters}/chapter2.vtf"
                "map" "sp_a2_laser_intro"
            }
            2
            {   
                "name" "#portal2_Chapter3_Title"
                "image" "file://{p2chapters}/chapter3.vtf"
                "map" "sp_a2_sphere_peek"
            }
            3
            {   
                "name" "#portal2_Chapter4_Title"
                "image" "file://{p2chapters}/chapter4.vtf"
                "map" "sp_a2_bts3"
            }
        }
    }

    "P2C"
    {
        "name" "Portal 2 Co-op"
        "icon" "file://{images}/menu/portal2/logo.png"
        "background" "file://{media}/menu_act01.webm"
        "publisher" "Valve"
        "maps"
        {
            0
            {   
                "name" "#portal2_Chapter1_Title"
                "image" "file://{p2chapters}/chapter1.vtf"
                "map" "sp_a1_intro1"
            }
        }
    }
}