name: Formatting

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Setup Node.js 22
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Formatting Checks
      run: npm run format:check

    - name: Linting Checks
      run: npm run lint:check 

    - name: TypeScript Build
      run: npm run build
