name: ESLint
on:
  push:
    branches: [main, new-menu]
  pull_request:
    branches: [main, new-menu]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run check
