name: "Optimize SVGs"
on:
  push:
    branches: [main, new-menu]
  pull_request:
    branches: [main, new-menu]
  workflow_dispatch:
    # nothing goes here

jobs:
  optimize-svgs:
    name: SVGs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ericcornelissen/svgo-action@v3
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
